[package]
name = "druid-crdt"
version = "0.1.0"
authors = ["Christoph <xarvix@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
ropey = "1.2"
im = "15.0"